name: Deploy to Azure Container Registry

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

env:
  AZURE_CONTAINER_REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
  AZURE_APP_SERVICE_NAME: ${{ secrets.AZURE_APP_SERVICE_NAME }}
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  IMAGE_NAME: chat-app
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from secret
        run: 'echo "$ENV" > src/.env'
        shell: bash
        env:
          ENV: ${{ secrets.ENV }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          cd src/
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/chat-app:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/chat-app:latest
